### ISSUE TITLE
Conditional type on raw instruction creator gets tied in knots

### ISSUE THREAD

**Issue by steveluscher** [solana-program/create-solana-program#19]
![image](https://github.com/solana-program/create-solana-program/assets/13243/40bff190-2d49-4467-a720-319e634080f5)

```
error TS2322:
  Type 'Address<TNonceAuthorityAddress>' is not assignable to type 
    'TNonceAuthorityAddress extends string ? Address<TNonceAuthorityAddress> : TNonceAuthorityAddress'.
```

I think the conditional is just getting all tied in knots. What if we eliminated the conditional in favour of this?

```ts
export declare function getAdvanceNonceAccountInstructionRaw<
    TProgram extends string = '11111111111111111111111111111111',
    /* CHANGED LINE */ TAccountNonceAccount extends string = string,
    /* CHANGED LINE */ TAccountRecentBlockhashesSysvar extends string = 'SysvarRecentB1ockHashes11111111111111111111',
    /* CHANGED LINE */ TAccountNonceAuthority extends string = string,
    TRemainingAccounts extends Array<IAccountMeta<string>> = [],
>(
    accounts: {
        /* CHANGED LINE */ nonceAccount: Address<TAccountNonceAccount> | IAccountMeta<TAccountNonceAccount>,
        /* CHANGED LINE */ recentBlockhashesSysvar?: Address<TAccountRecentBlockhashesSysvar> | IAccountMeta<TAccountRecentBlockhashesSysvar>,
        /* CHANGED LINE */ nonceAuthority: Address<TAccountNonceAuthority> | IAccountMeta<TAccountNonceAuthority>,
    },
    programAddress?: Address<TProgram>,
    remainingAccounts?: TRemainingAccounts,
): AdvanceNonceAccountInstruction<TProgram, TAccountNonceAccount, TAccountRecentBlockhashesSysvar, TAccountNonceAuthority, TRemainingAccounts>;
```

**Comment by steveluscher** [comment]
Oof. I think I know what's going on here. This is the thing where you want to be able to either say:

* here's a string; create the default _kind_ of `IAccountMeta` with that address, or
* here's a _concrete_ `IAccountMeta`; please use that one I know what I'm doing.

**Comment by lorisleiva** [comment]
Yeah IIRC I had it like you mentioned in the OP before but TypeScript was not correctly inferring the type parameters and was just using the default `string` type all the time.

**Comment by steveluscher** [comment]
Oh, this change definitely _works_ and infers everything correctly. If you don't _need_ the ‘`IAccountMeta` override’ capability, then I think the change is doable.

Something like [this](https://gist.github.com/steveluscher/9a262db2584a2fce3825b10938e4ec87) (I don't know what I'm doing).

**Comment by lorisleiva** [comment]
Yeah that's what I mean though it doesn't work with the account meta override. We do need that even within the other generated functions though.

Unless you can see another way of doing that override?

**Comment by steveluscher** [comment]
This really belongs over at https://github.com/metaplex-foundation/kinobi/issues/174. Let's continue the discussion there!
